---
# task/add_ssh_keys file for provision_management_user
- name: "Add key to authorized_keys"
  ansible.posix.authorized_key:
    user: "{{ provision_management_user_name }}"
    key: "{{ provision_management_user_ssh_key }}"
    comment: "{{ provision_management_user_name }}@{{ ansible_hostname }}"
    key_options: "{{ provision_management_user_ssh_key_options }}"
    exclusive: "{{ provision_management_user_ssh_key_exclusive }}"
  become: true
